Vagrant.configure(2) do |config|
  config.vm.box = "centos65-x86_64-20140116"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
